data_ingestion:
  raw_data_path: data/raw/loan_approval.csv
  train_data_path: data/processed/train.csv
  test_data_path: data/processed/test.csv
  test_size: 0.2
  random_state: 42
  data_validation:
  required_columns:
    - loan_id
    - no_of_dependents
    - education
    - self_employed
    - income_annum
    - loan_amount
    - loan_term
    - cibil_score
    - residential_assets_value
    - commercial_assets_value
    - luxury_assets_value
    - bank_asset_value
    - loan_status